### ISSUE TITLE
Anti-pop switching for Vactrol expander

### ISSUE THREAD

**Issue by n6smith** [Skrylar/skylights-vcv#2]
It seems that the Vactrol module is prone to some (quite loud at times) 'clicking'... especially when handling, though not limited to, lower pitched sounds... Any chance this could be eliminated or if not, then smoothed out a bit to reduce the clicks?

**Comment by Skrylar** [comment]
If you can provide one or more .vcv files that exhibit the issue and I can confirm it on my side, then yes.

**Comment by n6smith** [comment]
By all means.. Two very generic VCV patches... One without and one with the vactrol. 'Clicking' only occurs when using the vactrol

[Vactrol click issue.zip](https://github.com/Skrylar/skylights-vcv/files/2928068/Vactrol.click.issue.zip)

**Comment by n6smith** [comment]
Just a quick followup....
Did the two files I sent you, help identify the cause of the 'clicking'?

**Comment by Skrylar** [comment]
It's switch popping, since the vactrol doesn't have any anti-popping mechanisms.

https://www.mrblackpedals.com/blogs/straight-jive/6629778-what-really-causes-switch-pop
