### ISSUE TITLE
Feature request: Switches expander, Bytes expander, Worng LPG expander

### ISSUE THREAD

**Issue by djpeterso23662** [Skrylar/skylights-vcv#3]
Hi @Skrylar! Thanks so much for your open-source Turing Machine and expander modules.  I have been wishing for these modules to go open source for ages, and I really appreciate your work and time that have gone into them.  

Have you thought about adding the Bytes, Switches, and Worng LPG expanders at some point?  I am currently trying to get a bunch of old Turing V1 and expander PCB's built, and have been trying to figure out if I want to tangle with Bytes and Switches.  It looks like coding them might be easier than building them!  Both look a bit tough, though at least the docs are good.  If you need all the PDFs, I spent some time dragging them out of the Way Back Machine and am happy to share.  

Again, thanks for your work on these modules!

David

**Comment by Skrylar** [comment]
I'm not familiar with these expanders.

**Comment by Skrylar** [comment]
> Bytes expander

Doable. Original module wants access to all 16-bits, and XPND only exposes 8-bits. Changing XPND would break older patches so is less than desirable.

Module would have to work on (a selectable portion of) the 8-bits. Might be fixable when Rack V1 comes out and we can use polyphonic cables to get the next eight without breaking anything.

> Switches expander

Seems straightforward. Only question is what is the difference between `fast IC switches` and `slow vactrol switches`.

> Worng LPG

~~So the vactrol mixer, with a different chipset. Hmm.~~ Took some digging to find that LPG stands for Low Pass Gate, which replaces the attenuator with a low pass filter instead.

**Comment by Skrylar** [comment]
> Seems straightforward. Only question is what is the difference between fast IC switches and slow vactrol switches.

Think I've figured this one out actually.

**Comment by djpeterso23662** [comment]
Thanks so much for looking into this, @Skrylar! I think you are going to come up with something very cool and useful!

**Comment by Skrylar** [comment]
#10 #9 #8
